# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2022_06_29_092541) do

  create_table "cleaning_work_columns", charset: "utf8mb3", force: :cascade do |t|
    t.integer "table_id"
    t.text "d1"
    t.text "d2"
    t.text "d3"
    t.text "d4"
    t.text "d5"
    t.text "d6"
    t.text "d7"
    t.text "d8"
    t.text "d9"
    t.text "d10"
    t.text "d11"
    t.text "d12"
    t.text "d13"
    t.text "d14"
    t.text "d15"
    t.text "d16"
    t.text "d17"
    t.text "d18"
    t.text "d19"
    t.text "d20"
    t.text "d21"
    t.text "d22"
    t.text "d23"
    t.text "d24"
    t.text "d25"
    t.text "d26"
    t.text "d27"
    t.text "d28"
    t.text "d29"
    t.text "d30"
    t.text "d31"
    t.text "d32"
    t.text "d33"
    t.text "d34"
    t.text "d35"
    t.text "d36"
    t.text "d37"
    t.text "d38"
    t.text "d39"
    t.text "d40"
    t.text "d41"
    t.text "d42"
    t.text "d43"
    t.text "d44"
    t.text "d45"
    t.text "d46"
    t.text "d47"
    t.text "d48"
    t.text "d49"
    t.text "d50"
    t.text "d51"
    t.text "d52"
    t.text "d53"
    t.text "d54"
    t.text "d55"
    t.text "d56"
    t.text "d57"
    t.text "d58"
    t.text "d59"
    t.text "d60"
    t.text "d61"
    t.text "d62"
    t.text "d63"
    t.text "d64"
    t.text "d65"
    t.text "d66"
    t.text "d67"
    t.text "d68"
    t.text "d69"
    t.text "d70"
    t.text "d71"
    t.text "d72"
    t.text "d73"
    t.text "d74"
    t.text "d75"
    t.text "d76"
    t.text "d77"
    t.text "d78"
    t.text "d79"
    t.text "d80"
    t.text "d81"
    t.text "d82"
    t.text "d83"
    t.text "d84"
    t.text "d85"
    t.text "d86"
    t.text "d87"
    t.text "d88"
    t.text "d89"
    t.text "d90"
    t.text "d91"
    t.text "d92"
    t.text "d93"
    t.text "d94"
    t.text "d95"
    t.text "d96"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "cleaning_works", charset: "utf8mb3", force: :cascade do |t|
    t.string "name"
    t.integer "time_required"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
  end

  create_table "deliver_work_columns", charset: "utf8mb3", force: :cascade do |t|
    t.integer "table_id"
    t.text "b1"
    t.text "b2"
    t.text "b3"
    t.text "b4"
    t.text "b5"
    t.text "b6"
    t.text "b7"
    t.text "b8"
    t.text "b9"
    t.text "b10"
    t.text "b11"
    t.text "b12"
    t.text "b13"
    t.text "b14"
    t.text "b15"
    t.text "b16"
    t.text "b17"
    t.text "b18"
    t.text "b19"
    t.text "b20"
    t.text "b21"
    t.text "b22"
    t.text "b23"
    t.text "b24"
    t.text "b25"
    t.text "b26"
    t.text "b27"
    t.text "b28"
    t.text "b29"
    t.text "b30"
    t.text "b31"
    t.text "b32"
    t.text "b33"
    t.text "b34"
    t.text "b35"
    t.text "b36"
    t.text "b37"
    t.text "b38"
    t.text "b39"
    t.text "b40"
    t.text "b41"
    t.text "b42"
    t.text "b43"
    t.text "b44"
    t.text "b45"
    t.text "b46"
    t.text "b47"
    t.text "b48"
    t.text "b49"
    t.text "b50"
    t.text "b51"
    t.text "b52"
    t.text "b53"
    t.text "b54"
    t.text "b55"
    t.text "b56"
    t.text "b57"
    t.text "b58"
    t.text "b59"
    t.text "b60"
    t.text "b61"
    t.text "b62"
    t.text "b63"
    t.text "b64"
    t.text "b65"
    t.text "b66"
    t.text "b67"
    t.text "b68"
    t.text "b69"
    t.text "b70"
    t.text "b71"
    t.text "b72"
    t.text "b73"
    t.text "b74"
    t.text "b75"
    t.text "b76"
    t.text "b77"
    t.text "b78"
    t.text "b79"
    t.text "b80"
    t.text "b81"
    t.text "b82"
    t.text "b83"
    t.text "b84"
    t.text "b85"
    t.text "b86"
    t.text "b87"
    t.text "b88"
    t.text "b89"
    t.text "b90"
    t.text "b91"
    t.text "b92"
    t.text "b93"
    t.text "b94"
    t.text "b95"
    t.text "b96"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "deliver_works", charset: "utf8mb3", force: :cascade do |t|
    t.string "name"
    t.integer "time_required"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
  end

  create_table "product_management_work_columns", charset: "utf8mb3", force: :cascade do |t|
    t.integer "table_id"
    t.text "c1"
    t.text "c2"
    t.text "c3"
    t.text "c4"
    t.text "c5"
    t.text "c6"
    t.text "c7"
    t.text "c8"
    t.text "c9"
    t.text "c10"
    t.text "c11"
    t.text "c12"
    t.text "c13"
    t.text "c14"
    t.text "c15"
    t.text "c16"
    t.text "c17"
    t.text "c18"
    t.text "c19"
    t.text "c20"
    t.text "c21"
    t.text "c22"
    t.text "c23"
    t.text "c24"
    t.text "c25"
    t.text "c26"
    t.text "c27"
    t.text "c28"
    t.text "c29"
    t.text "c30"
    t.text "c31"
    t.text "c32"
    t.text "c33"
    t.text "c34"
    t.text "c35"
    t.text "c36"
    t.text "c37"
    t.text "c38"
    t.text "c39"
    t.text "c40"
    t.text "c41"
    t.text "c42"
    t.text "c43"
    t.text "c44"
    t.text "c45"
    t.text "c46"
    t.text "c47"
    t.text "c48"
    t.text "c49"
    t.text "c50"
    t.text "c51"
    t.text "c52"
    t.text "c53"
    t.text "c54"
    t.text "c55"
    t.text "c56"
    t.text "c57"
    t.text "c58"
    t.text "c59"
    t.text "c60"
    t.text "c61"
    t.text "c62"
    t.text "c63"
    t.text "c64"
    t.text "c65"
    t.text "c66"
    t.text "c67"
    t.text "c68"
    t.text "c69"
    t.text "c70"
    t.text "c71"
    t.text "c72"
    t.text "c73"
    t.text "c74"
    t.text "c75"
    t.text "c76"
    t.text "c77"
    t.text "c78"
    t.text "c79"
    t.text "c80"
    t.text "c81"
    t.text "c82"
    t.text "c83"
    t.text "c84"
    t.text "c85"
    t.text "c86"
    t.text "c87"
    t.text "c88"
    t.text "c89"
    t.text "c90"
    t.text "c91"
    t.text "c92"
    t.text "c93"
    t.text "c94"
    t.text "c95"
    t.text "c96"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "product_management_works", charset: "utf8mb3", force: :cascade do |t|
    t.string "name"
    t.integer "time_required"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
  end

  create_table "regular_work_columns", charset: "utf8mb3", force: :cascade do |t|
    t.integer "table_id"
    t.text "a1"
    t.text "a2"
    t.text "a3"
    t.text "a4"
    t.text "a5"
    t.text "a6"
    t.text "a7"
    t.text "a8"
    t.text "a9"
    t.text "a10"
    t.text "a11"
    t.text "a12"
    t.text "a13"
    t.text "a14"
    t.text "a15"
    t.text "a16"
    t.text "a17"
    t.text "a18"
    t.text "a19"
    t.text "a20"
    t.text "a21"
    t.text "a22"
    t.text "a23"
    t.text "a24"
    t.text "a25"
    t.text "a26"
    t.text "a27"
    t.text "a28"
    t.text "a29"
    t.text "a30"
    t.text "a31"
    t.text "a32"
    t.text "a33"
    t.text "a34"
    t.text "a35"
    t.text "a36"
    t.text "a37"
    t.text "a38"
    t.text "a39"
    t.text "a40"
    t.text "a41"
    t.text "a42"
    t.text "a43"
    t.text "a44"
    t.text "a45"
    t.text "a46"
    t.text "a47"
    t.text "a48"
    t.text "a49"
    t.text "a50"
    t.text "a51"
    t.text "a52"
    t.text "a53"
    t.text "a54"
    t.text "a55"
    t.text "a56"
    t.text "a57"
    t.text "a58"
    t.text "a59"
    t.text "a60"
    t.text "a61"
    t.text "a62"
    t.text "a63"
    t.text "a64"
    t.text "a65"
    t.text "a66"
    t.text "a67"
    t.text "a68"
    t.text "a69"
    t.text "a70"
    t.text "a71"
    t.text "a72"
    t.text "a73"
    t.text "a74"
    t.text "a75"
    t.text "a76"
    t.text "a77"
    t.text "a78"
    t.text "a79"
    t.text "a80"
    t.text "a81"
    t.text "a82"
    t.text "a83"
    t.text "a84"
    t.text "a85"
    t.text "a86"
    t.text "a87"
    t.text "a88"
    t.text "a89"
    t.text "a90"
    t.text "a91"
    t.text "a92"
    t.text "a93"
    t.text "a94"
    t.text "a95"
    t.text "a96"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "regular_works", charset: "utf8mb3", force: :cascade do |t|
    t.string "name"
    t.integer "time_required"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
  end

  create_table "rows", charset: "utf8mb3", force: :cascade do |t|
    t.string "regular_work"
    t.string "deliver_work"
    t.string "product_management_work"
    t.string "cleaning_work"
    t.integer "table_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "user_id"
  end

  create_table "tables", charset: "utf8mb3", force: :cascade do |t|
    t.string "title"
    t.integer "user_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "users", charset: "utf8mb3", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
