class CreateCleaningWorkColumns < ActiveRecord::Migration[6.1]
  def change
    create_table :cleaning_work_columns do |t|
      t.integer :table_id
      t.text :d1
      t.text :d2
      t.text :d3
      t.text :d4
      t.text :d5
      t.text :d6
      t.text :d7
      t.text :d8
      t.text :d9
      t.text :d10
      t.text :d11
      t.text :d12
      t.text :d13
      t.text :d14
      t.text :d15
      t.text :d16
      t.text :d17
      t.text :d18
      t.text :d19
      t.text :d20
      t.text :d21
      t.text :d22
      t.text :d23
      t.text :d24
      t.text :d25
      t.text :d26
      t.text :d27
      t.text :d28
      t.text :d29
      t.text :d30
      t.text :d31
      t.text :d32
      t.text :d33
      t.text :d34
      t.text :d35
      t.text :d36
      t.text :d37
      t.text :d38
      t.text :d39
      t.text :d40
      t.text :d41
      t.text :d42
      t.text :d43
      t.text :d44
      t.text :d45
      t.text :d46
      t.text :d47
      t.text :d48
      t.text :d49
      t.text :d50
      t.text :d51
      t.text :d52
      t.text :d53
      t.text :d54
      t.text :d55
      t.text :d56
      t.text :d57
      t.text :d58
      t.text :d59
      t.text :d60
      t.text :d61
      t.text :d62
      t.text :d63
      t.text :d64
      t.text :d65
      t.text :d66
      t.text :d67
      t.text :d68
      t.text :d69
      t.text :d70
      t.text :d71
      t.text :d72
      t.text :d73
      t.text :d74
      t.text :d75
      t.text :d76
      t.text :d77
      t.text :d78
      t.text :d79
      t.text :d80
      t.text :d81
      t.text :d82
      t.text :d83
      t.text :d84
      t.text :d85
      t.text :d86
      t.text :d87
      t.text :d88
      t.text :d89
      t.text :d90
      t.text :d91
      t.text :d92
      t.text :d93
      t.text :d94
      t.text :d95
      t.text :d96

      t.timestamps
    end
  end
end
