class CreateDeliverWorkColumns < ActiveRecord::Migration[6.1]
  def change
    create_table :deliver_work_columns do |t|
      t.integer :table_id
      t.text :b1
      t.text :b2
      t.text :b3
      t.text :b4
      t.text :b5
      t.text :b6
      t.text :b7
      t.text :b8
      t.text :b9
      t.text :b10
      t.text :b11
      t.text :b12
      t.text :b13
      t.text :b14
      t.text :b15
      t.text :b16
      t.text :b17
      t.text :b18
      t.text :b19
      t.text :b20
      t.text :b21
      t.text :b22
      t.text :b23
      t.text :b24
      t.text :b25
      t.text :b26
      t.text :b27
      t.text :b28
      t.text :b29
      t.text :b30
      t.text :b31
      t.text :b32
      t.text :b33
      t.text :b34
      t.text :b35
      t.text :b36
      t.text :b37
      t.text :b38
      t.text :b39
      t.text :b40
      t.text :b41
      t.text :b42
      t.text :b43
      t.text :b44
      t.text :b45
      t.text :b46
      t.text :b47
      t.text :b48
      t.text :b49
      t.text :b50
      t.text :b51
      t.text :b52
      t.text :b53
      t.text :b54
      t.text :b55
      t.text :b56
      t.text :b57
      t.text :b58
      t.text :b59
      t.text :b60
      t.text :b61
      t.text :b62
      t.text :b63
      t.text :b64
      t.text :b65
      t.text :b66
      t.text :b67
      t.text :b68
      t.text :b69
      t.text :b70
      t.text :b71
      t.text :b72
      t.text :b73
      t.text :b74
      t.text :b75
      t.text :b76
      t.text :b77
      t.text :b78
      t.text :b79
      t.text :b80
      t.text :b81
      t.text :b82
      t.text :b83
      t.text :b84
      t.text :b85
      t.text :b86
      t.text :b87
      t.text :b88
      t.text :b89
      t.text :b90
      t.text :b91
      t.text :b92
      t.text :b93
      t.text :b94
      t.text :b95
      t.text :b96

      t.timestamps
    end
  end
end
