class CreateRegularWorkColumns < ActiveRecord::Migration[6.1]
  def change
    create_table :regular_work_columns do |t|
      t.integer :table_id
      t.text :a1
      t.text :a2
      t.text :a3
      t.text :a4
      t.text :a5
      t.text :a6
      t.text :a7
      t.text :a8
      t.text :a9
      t.text :a10
      t.text :a11
      t.text :a12
      t.text :a13
      t.text :a14
      t.text :a15
      t.text :a16
      t.text :a17
      t.text :a18
      t.text :a19
      t.text :a20
      t.text :a21
      t.text :a22
      t.text :a23
      t.text :a24
      t.text :a25
      t.text :a26
      t.text :a27
      t.text :a28
      t.text :a29
      t.text :a30
      t.text :a31
      t.text :a32
      t.text :a33
      t.text :a34
      t.text :a35
      t.text :a36
      t.text :a37
      t.text :a38
      t.text :a39
      t.text :a40
      t.text :a41
      t.text :a42
      t.text :a43
      t.text :a44
      t.text :a45
      t.text :a46
      t.text :a47
      t.text :a48
      t.text :a49
      t.text :a50
      t.text :a51
      t.text :a52
      t.text :a53
      t.text :a54
      t.text :a55
      t.text :a56
      t.text :a57
      t.text :a58
      t.text :a59
      t.text :a60
      t.text :a61
      t.text :a62
      t.text :a63
      t.text :a64
      t.text :a65
      t.text :a66
      t.text :a67
      t.text :a68
      t.text :a69
      t.text :a70
      t.text :a71
      t.text :a72
      t.text :a73
      t.text :a74
      t.text :a75
      t.text :a76
      t.text :a77
      t.text :a78
      t.text :a79
      t.text :a80
      t.text :a81
      t.text :a82
      t.text :a83
      t.text :a84
      t.text :a85
      t.text :a86
      t.text :a87
      t.text :a88
      t.text :a89
      t.text :a90
      t.text :a91
      t.text :a92
      t.text :a93
      t.text :a94
      t.text :a95
      t.text :a96

      t.timestamps
    end
  end
end
