class CreateProductManagementWorkColumns < ActiveRecord::Migration[6.1]
  def change
    create_table :product_management_work_columns do |t|
      t.integer :table_id
      t.text :c1
      t.text :c2
      t.text :c3
      t.text :c4
      t.text :c5
      t.text :c6
      t.text :c7
      t.text :c8
      t.text :c9
      t.text :c10
      t.text :c11
      t.text :c12
      t.text :c13
      t.text :c14
      t.text :c15
      t.text :c16
      t.text :c17
      t.text :c18
      t.text :c19
      t.text :c20
      t.text :c21
      t.text :c22
      t.text :c23
      t.text :c24
      t.text :c25
      t.text :c26
      t.text :c27
      t.text :c28
      t.text :c29
      t.text :c30
      t.text :c31
      t.text :c32
      t.text :c33
      t.text :c34
      t.text :c35
      t.text :c36
      t.text :c37
      t.text :c38
      t.text :c39
      t.text :c40
      t.text :c41
      t.text :c42
      t.text :c43
      t.text :c44
      t.text :c45
      t.text :c46
      t.text :c47
      t.text :c48
      t.text :c49
      t.text :c50
      t.text :c51
      t.text :c52
      t.text :c53
      t.text :c54
      t.text :c55
      t.text :c56
      t.text :c57
      t.text :c58
      t.text :c59
      t.text :c60
      t.text :c61
      t.text :c62
      t.text :c63
      t.text :c64
      t.text :c65
      t.text :c66
      t.text :c67
      t.text :c68
      t.text :c69
      t.text :c70
      t.text :c71
      t.text :c72
      t.text :c73
      t.text :c74
      t.text :c75
      t.text :c76
      t.text :c77
      t.text :c78
      t.text :c79
      t.text :c80
      t.text :c81
      t.text :c82
      t.text :c83
      t.text :c84
      t.text :c85
      t.text :c86
      t.text :c87
      t.text :c88
      t.text :c89
      t.text :c90
      t.text :c91
      t.text :c92
      t.text :c93
      t.text :c94
      t.text :c95
      t.text :c96

      t.timestamps
    end
  end
end
